package nl.daedalus.engine.input;

public class KeyCodes {

    public static final int
            DAE_KEY_SPACE         = 32,
            DAE_KEY_APOSTROPHE    = 39,
            DAE_KEY_COMMA         = 44,
            DAE_KEY_MINUS         = 45,
            DAE_KEY_PERIOD        = 46,
            DAE_KEY_SLASH         = 47,
            DAE_KEY_0             = 48,
            DAE_KEY_1             = 49,
            DAE_KEY_2             = 50,
            DAE_KEY_3             = 51,
            DAE_KEY_4             = 52,
            DAE_KEY_5             = 53,
            DAE_KEY_6             = 54,
            DAE_KEY_7             = 55,
            DAE_KEY_8             = 56,
            DAE_KEY_9             = 57,
            DAE_KEY_SEMICOLON     = 59,
            DAE_KEY_EQUAL         = 61,
            DAE_KEY_A             = 65,
            DAE_KEY_B             = 66,
            DAE_KEY_C             = 67,
            DAE_KEY_D             = 68,
            DAE_KEY_E             = 69,
            DAE_KEY_F             = 70,
            DAE_KEY_G             = 71,
            DAE_KEY_H             = 72,
            DAE_KEY_I             = 73,
            DAE_KEY_J             = 74,
            DAE_KEY_K             = 75,
            DAE_KEY_L             = 76,
            DAE_KEY_M             = 77,
            DAE_KEY_N             = 78,
            DAE_KEY_O             = 79,
            DAE_KEY_P             = 80,
            DAE_KEY_Q             = 81,
            DAE_KEY_R             = 82,
            DAE_KEY_S             = 83,
            DAE_KEY_T             = 84,
            DAE_KEY_U             = 85,
            DAE_KEY_V             = 86,
            DAE_KEY_W             = 87,
            DAE_KEY_X             = 88,
            DAE_KEY_Y             = 89,
            DAE_KEY_Z             = 90,
            DAE_KEY_LEFT_BRACKET  = 91,
            DAE_KEY_BACKSLASH     = 92,
            DAE_KEY_RIGHT_BRACKET = 93,
            DAE_KEY_GRAVE_ACCENT  = 96,
            DAE_KEY_WORLD_1       = 161,
            DAE_KEY_WORLD_2       = 162;

    /** Function keys. */
    public static final int
            DAE_KEY_ESCAPE        = 256,
            DAE_KEY_ENTER         = 257,
            DAE_KEY_TAB           = 258,
            DAE_KEY_BACKSPACE     = 259,
            DAE_KEY_INSERT        = 260,
            DAE_KEY_DELETE        = 261,
            DAE_KEY_RIGHT         = 262,
            DAE_KEY_LEFT          = 263,
            DAE_KEY_DOWN          = 264,
            DAE_KEY_UP            = 265,
            DAE_KEY_PAGE_UP       = 266,
            DAE_KEY_PAGE_DOWN     = 267,
            DAE_KEY_HOME          = 268,
            DAE_KEY_END           = 269,
            DAE_KEY_CAPS_LOCK     = 280,
            DAE_KEY_SCROLL_LOCK   = 281,
            DAE_KEY_NUM_LOCK      = 282,
            DAE_KEY_PRINT_SCREEN  = 283,
            DAE_KEY_PAUSE         = 284,
            DAE_KEY_F1            = 290,
            DAE_KEY_F2            = 291,
            DAE_KEY_F3            = 292,
            DAE_KEY_F4            = 293,
            DAE_KEY_F5            = 294,
            DAE_KEY_F6            = 295,
            DAE_KEY_F7            = 296,
            DAE_KEY_F8            = 297,
            DAE_KEY_F9            = 298,
            DAE_KEY_F10           = 299,
            DAE_KEY_F11           = 300,
            DAE_KEY_F12           = 301,
            DAE_KEY_F13           = 302,
            DAE_KEY_F14           = 303,
            DAE_KEY_F15           = 304,
            DAE_KEY_F16           = 305,
            DAE_KEY_F17           = 306,
            DAE_KEY_F18           = 307,
            DAE_KEY_F19           = 308,
            DAE_KEY_F20           = 309,
            DAE_KEY_F21           = 310,
            DAE_KEY_F22           = 311,
            DAE_KEY_F23           = 312,
            DAE_KEY_F24           = 313,
            DAE_KEY_F25           = 314,
            DAE_KEY_KP_0          = 320,
            DAE_KEY_KP_1          = 321,
            DAE_KEY_KP_2          = 322,
            DAE_KEY_KP_3          = 323,
            DAE_KEY_KP_4          = 324,
            DAE_KEY_KP_5          = 325,
            DAE_KEY_KP_6          = 326,
            DAE_KEY_KP_7          = 327,
            DAE_KEY_KP_8          = 328,
            DAE_KEY_KP_9          = 329,
            DAE_KEY_KP_DECIMAL    = 330,
            DAE_KEY_KP_DIVIDE     = 331,
            DAE_KEY_KP_MULTIPLY   = 332,
            DAE_KEY_KP_SUBTRACT   = 333,
            DAE_KEY_KP_ADD        = 334,
            DAE_KEY_KP_ENTER      = 335,
            DAE_KEY_KP_EQUAL      = 336,
            DAE_KEY_LEFT_SHIFT    = 340,
            DAE_KEY_LEFT_CONTROL  = 341,
            DAE_KEY_LEFT_ALT      = 342,
            DAE_KEY_LEFT_SUPER    = 343,
            DAE_KEY_RIGHT_SHIFT   = 344,
            DAE_KEY_RIGHT_CONTROL = 345,
            DAE_KEY_RIGHT_ALT     = 346,
            DAE_KEY_RIGHT_SUPER   = 347,
            DAE_KEY_MENU          = 348,
            DAE_KEY_LAST          = DAE_KEY_MENU;

    public static final int DAE_MOD_SHIFT = 0x1;

    public static final int DAE_MOD_CONTROL = 0x2;

    public static final int DAE_MOD_ALT = 0x4;

    public static final int DAE_MOD_SUPER = 0x8;

    public static final int DAE_MOD_CAPS_LOCK = 0x10;

    public static final int DAE_MOD_NUM_LOCK = 0x20;

    public static final int
            DAE_MOUSE_BUTTON_1      = 0,
            DAE_MOUSE_BUTTON_2      = 1,
            DAE_MOUSE_BUTTON_3      = 2,
            DAE_MOUSE_BUTTON_4      = 3,
            DAE_MOUSE_BUTTON_5      = 4,
            DAE_MOUSE_BUTTON_6      = 5,
            DAE_MOUSE_BUTTON_7      = 6,
            DAE_MOUSE_BUTTON_8      = 7,
            DAE_MOUSE_BUTTON_LAST   = DAE_MOUSE_BUTTON_8,
            DAE_MOUSE_BUTTON_LEFT   = DAE_MOUSE_BUTTON_1,
            DAE_MOUSE_BUTTON_RIGHT  = DAE_MOUSE_BUTTON_2,
            DAE_MOUSE_BUTTON_MIDDLE = DAE_MOUSE_BUTTON_3;

}
